# Generated by Django 5.0.6 on 2024-06-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_tr',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
